version: '3.9'

services:
  postgres:
    image: postgres
    container_name: practice_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  mongo:
    image: mongo:latest
    container_name: practice_mongo
    restart: always
    ports:
      - 27017:27017