version: '3'

services:
  pg_master:
    image: bitnami/postgresql
    container_name: pg_master
    ports:
      - '5555:5432'
    volumes:
      - ../PostgreSQL:/docker-entrypoint-initdb.d
    environment:
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: ${POSTGRES_USER}
      POSTGRESQL_REPLICATION_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_DATABASE: postgres

  pg_replica:
    image: bitnami/postgresql
    container_name: pg_replica
    ports:
      - '5556:5432'
    depends_on:
      - pg_master
    environment:
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_REPLICATION_USER: ${POSTGRES_USER}
      POSTGRESQL_REPLICATION_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_MASTER_HOST: pg_master
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}

  pgpool_1:
    image: bitnami/pgpool
    container_name: pgpool_1
    ports:
      - '5560:5432'
    depends_on:
      - pg_master
    environment:
      PGPOOL_BACKEND_NODES: 0:pg_master:5432,1:pg_replica:5432
      PGPOOL_POSTGRES_USERNAME: ${POSTGRES_USER}
      PGPOOL_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPOOL_ADMIN_USERNAME: ${POSTGRES_USER}
      PGPOOL_ADMIN_PASSWORD: ${POSTGRES_PASSWORD}
      PGPOOL_ENABLE_LOAD_BALANCING: yes
      PGPOOL_ENABLE_STATEMENT_LOAD_BALANCING: yes
      PGPOOL_NUM_INIT_CHILDREN: 10
      PGPOOL_SR_CHECK_USER: ${POSTGRES_USER}
      PGPOOL_SR_CHECK_PASSWORD: ${POSTGRES_PASSWORD}
      PGPOOL_HEALTH_CHECK_MAX_RETRIES: 1

  pgpool_2:
    image: bitnami/pgpool
    container_name: pgpool_2
    ports:
      - '5570:5432'
    depends_on:
      - pg_master
    environment:
      PGPOOL_BACKEND_NODES: 0:pg_master:5432,1:pg_replica:5432
      PGPOOL_POSTGRES_USERNAME: ${POSTGRES_USER}
      PGPOOL_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPOOL_ADMIN_USERNAME: ${POSTGRES_USER}
      PGPOOL_ADMIN_PASSWORD: ${POSTGRES_PASSWORD}
      PGPOOL_ENABLE_LOAD_BALANCING: yes
      PGPOOL_ENABLE_STATEMENT_LOAD_BALANCING: yes
      PGPOOL_NUM_INIT_CHILDREN: 10
      PGPOOL_SR_CHECK_USER: ${POSTGRES_USER}
      PGPOOL_SR_CHECK_PASSWORD: ${POSTGRES_PASSWORD}
      PGPOOL_HEALTH_CHECK_MAX_RETRIES: 1

  cassandra:
    container_name: cassandra
    image: cassandra
    ports:
      - '7000:7000'
      - '9042:9042'
    environment:
      - 'MAX_HEAP_SIZE=256M'
      - 'HEAP_NEWSIZE=128M'
    restart: no

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra
    depends_on:
      - cassandra
    volumes:
      - ./init-scripts/cassandra/schema.cql:/schema.cql
    command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"

  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'

  flask_app:
    container_name: flaskapp
    image: python:3.10
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../Application:/app
    depends_on:
      - cassandra
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    volumes:
      - ../Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - flask_app


