
version: '3'

services:

  postgres:
    image: postgres
    container_name: practice_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
     - ../PostgreSQL:/docker-entrypoint-initdb.d

  cassandra:
    container_name: cassandra
    image: cassandra
    ports:
      - 7000:7000
      - 9042:9042
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: no
    
  cassandra-load-keyspace:
      container_name: cassandra-load-keyspace
      image: cassandra:latest
      depends_on:
        - cassandra
      volumes:
        - ./init-scripts/cassandra/schema.cql:/schema.cql 
      command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"
  
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'

  web:
    build: 
      dockerfile: ../Application/Dockerfile
      context: ../Application
    env_file:
      - .env
    ports:
      - 3000:3000
